### ISSUE TITLE
Feature suggestion: Subtitle in book details

### ISSUE THREAD

**Issue by mika-n** [AndrewBennet/ReadingList#28]
Hi. Thanks for useful app to keep track of books read or wanted to read. There are several apps doing the same thing, but this app has couple features which makes it to stand out from rest of the apps.  

The ability to add custom books with author/title/description and a cover image (taken with a camera or choosing from a gallery) is something which is often missing in other apps. This is excellent feature when reading non-english books because often search engine doesn't find for example books written in Finnish. 

I do have couple feature suggestions. Many books are part of a series, so the title itself isn't always the "only title" attached to a book. Could there be an option to set a subtitle to a book also? This way we could add "series name #X" subtitles. It could be an optional entry below Title field in a detail editor. 

A book list view could then show this as "War cry - Courtney #14. Smith, Wilbur" title when an optional subtitle is entered for a book. And the list view could use it as a optional sort field also.

Anyway. Thanks for the app and keep up the good work.

**Comment by AndrewBennet** [comment]
Thanks for the suggestion. This sounds like a good feature, and should be straight-forward to add. Google Books also seems to have a subtitle field available sometimes, which I could use when populating book data from a search or lookup:

![image](https://user-images.githubusercontent.com/2078225/56358496-ade6f200-61d6-11e9-9591-fceb2052e210.png)

I'll look into adding this in a future release!

**Comment by mika-n** [comment]
The latest version has Subtitle support. Great.
But, how about having a small tweak to sort order of ToRead and Finished book lists. Now there is a sort order "Title". I guess this is the main title only.

Maybe the existing "Title" sort order could be "Title - Subtitle" ordering and then a new sort option with "Subtitle - Title" sorting logic?

This way it would be possible to sort and and find books based on title or subtitle value.

**Comment by mika-n** [comment]
@AndrewBennet  Any chances to have the Title-Subtitle vs Subtitle-Title sort order feature described in the previous post? Thx.

**Comment by AndrewBennet** [comment]
Thanks for the reminder - I'll see if I can add this to the next update 👍

**Comment by AndrewBennet** [comment]
Added this sort in 9e67bc5aaa3b45b9cb832bc787fc7845793e4857 - I'll release the latest version to TestFlight soon

**Comment by mika-n** [comment]
Thx. Subtitle sorting seems to be working great.
