### ISSUE TITLE
Feature suggestion: Show an info icon/button in search lists to see book details BEFORE adding a book to own library 

### ISSUE THREAD

**Issue by mika-n** [AndrewBennet/ReadingList#29]
The app has a good built-in search capabilities to search books by ISBN#, title, author and so on.
Sometimes the search list doesn't find a book or even when it finds the one I'm looking for then there may be some other potentially interesting looking books in the result list. However, the search list doesn't let me see book details before adding the book to a personal library. If I find that "no, this is not a book I'm interested in after all" then I have to remove it from a library. 

It would be much easier if the search list would have an information icon or button and by pressing this button the app would show book details without first adding it to a personal library. If the book still looks interesting then there would be an another button to add it to "books to read / read books" lists. Of course the existing functionality could be still supported if this "info" button would be just an additional button on the same line with a book title in search result lists.

**Comment by AndrewBennet** [comment]
Thanks for the suggestion! 

I had been wondering about having a general setting to specify whether selecting a searched-for book should go through the "book metadata" step, or - as they do at the moment - jump straight to the "book read dates" step. However, I think your idea of having a separate button to see the details is better. I will look into adding this 👍

**Comment by AndrewBennet** [comment]
I've made progress on adding this feature. The Seach Online screen now shows a detail button by each result. Tapping this will bring the user to the book metadata screen (where they can tap Next to get to the book read state screen, and confirm the addition of the book).
<img src="https://user-images.githubusercontent.com/2078225/56495904-26a7c000-64ef-11e9-9d67-bf0f5fea5a1c.png" width="300" />

**Comment by mika-n** [comment]
This looks great and greatly improves the search screen functionality. Looking forward to see an updated version of the app.

**Comment by AndrewBennet** [comment]
👍 thanks for the feedback. I'll release a beta version soon: if you're on the TestFlight beta program you'll be able to try it out before the regular app store release, which will be a bit later
