### ISSUE TITLE
Reading List

### ISSUE THREAD

**Issue by Busenitz** [AndrewBennet/ReadingList#38]
Is there a way to search for a book by title or author?  If not, that would be great to have added.  Otherwise, the app is awesome.  I really love being able to search online for a book and have all of the basic info added automatically.  Thanks!

**Comment by bryanjclark** [comment]
Yeah, it's in there! Tap the `+` button in the top-right corner of the "To Read" tab, then choose "Search Online" and you can type an author, title, or whatever in there!
