### ISSUE TITLE
Book Description contains HTML entities &lt; &gt;

### ISSUE THREAD

**Issue by johnjkim** [AndrewBennet/ReadingList#39]
![pic](https://user-images.githubusercontent.com/2433422/73425517-b54f3600-42e6-11ea-9550-81c08bfbbd35.png)

**Comment by AndrewBennet** [comment]
Thanks for raising this. It looks like this book has HTML data within the Google book description field, which is unusual. See: https://books.google.co.uk/books?id=GVxwDwAAQBAJ

When I request this book's data from the Google Books API, I see the escaped HTML tags that you see: https://www.googleapis.com/books/v1/volumes/GVxwDwAAQBAJ

I'm not sure what the best way of handling this is - if there is anything better than doing nothing! I certainly can't assume that the description text contains escaped HTML tags, as most don't. Stripping them out would also be tricky, as I can't easily tell programatically what the description is _meant_ to look like. What if the escaped tags are meant to be there? For example, if a description was as follows:
> Escaping HTML entities is sometimes required. For example, the HTML tag &lt;i&gt; is escaped to \`\&lt;i\&gt;\`

in this case it should be left alone! 

I think the ideal solution in this case is for Google Books to fix their metadata, but I'm not aware of a mechanism to report this to them...
