### ISSUE TITLE
Enable iCloud backup

### ISSUE THREAD

**Issue by hugolundin** [AndrewBennet/ReadingList#4]
While we are waiting for iCloud sync to be finished I think it would be great to enable iCloud backup of the core data database, so it is part of the device backup (for example data is persisted between deletions of the app). 

As I understand it should simply be to enable iCloud for the app for this to work. I can if you want take a deeper look at the documentation or even try it out and send a pull request.

Thank you for a great app!

**Comment by AndrewBennet** [comment]
Hi - thanks for the suggestion. The app’s Core Data store is actually already included in device backups. So device restores from backups will include the books. However, app deletion _does_ cause these files to be removed. The only way to use a backed-up set of data is to set up a device from a backup - reinstalling the app won’t do the trick, annoyingly.

I know loss of books has been a problem for some users who did not have iCloud backups enabled - so the ability to separately export a backup save of the actual database files could be useful, and something I hadn’t considered before. It could even work similarly to WhatsApp’s backup feature - the whole database is saved to iCloud periodically, and when you first launch WhatsApp you get the option of restoring from the detected backup file.

I’ll look into this a little more!

**Comment by hugolundin** [comment]
Seems reasonable! With the backup inclusion in mind I guess I feel a little safer using the app.

**Comment by mika-n** [comment]
Are custom cover images also stored with device backups? Or just details what is included in exported CSV file?

**Comment by AndrewBennet** [comment]
Device backups _do_ include the cover image.

When you export a CSV, all the information about custom cover images is... not included. I realise it's not perfect. I did briefly wonder about specifying some kind of .zip or .tar format, which would allow the CSV to reference an associated image file, but to be honest I just never got around to looking into that solution.

When I finally get iCloud sync working, this should remove the need for this!
