### ISSUE TITLE
First image not showing on README

### ISSUE THREAD

**Issue by knjk04** [AndrewBennet/ReadingList#42]
The first image in the README is not displaying for me (see below). I've tried another browser and even another OS.

![image](https://user-images.githubusercontent.com/11173328/85206043-1c619b80-b317-11ea-9b67-b771435da2c7.png)

**Comment by AndrewBennet** [comment]
Thanks for raising this. This image went missing when I redesigned the website https://readinglist.app - which is where the image was pointing originally. I've dug out the original image and put in in this repo instead - it's displaying correctly now.
