### ISSUE TITLE
Unable to import books as finished

### ISSUE THREAD

**Issue by KPMonkey** [AndrewBennet/ReadingList#43]
I am unable to import a book and have it show on the "Finished" tab instead of under the "To Read" tab.

I have tried setting Started Reading, Finished Reading, Current Page, Current Percentage in the csv file before importing.

**Comment by AndrewBennet** [comment]
Sorry for the trouble you're having. It should appear in the Finished tab if there is both a Started Reading and a Finished Reading column - but these must be provided in the form YYYY-MM-DD - e.g. 2020-06-30. Also, Finished must be after Started. 

I realise this isn't properly explained in the app, so I am actually working on an improvement which will explain a lot more details about the import columns and how they should be provided. See the attached screenshot.

<img width="871" alt="Screenshot 2020-06-30 at 22 39 40" src="https://user-images.githubusercontent.com/2078225/86179677-a7fed780-bb22-11ea-8580-c463c3c19ec5.png">

**Comment by KPMonkey** [comment]
Awesome, that worked.

I looked through the code and overlooked the date format. And excel doesn't help as after you export it defaults to mm/dd/yyyy.

The column description update is a great addition.
