### ISSUE TITLE
I don't see file ReadingList.xcodeproj

### ISSUE THREAD

**Issue by quocphong1591** [AndrewBennet/ReadingList#49]
Hi, i downloaded source code but i don't find file ReadingList.xcodeproj. Please help me. Thanks

**Comment by AndrewBennet** [comment]
The xcodeproj file isn’t included in the git repository as it is [generated using xcodegen](https://github.com/AndrewBennet/ReadingList#xcodegen). I chose to do this as I was getting nasty merge conflicts with the xcodeproj file; instead, the xcodeproj file is reliably regenerated from the definition in project.yml. The readme has instructions on how to set up the project - let me know if you encounter any other issues!

**Comment by quocphong1591** [comment]
Thanks soo much ^^
