### ISSUE TITLE
[featurerequest] New features and a website

### ISSUE THREAD

**Issue by Farhaduneci** [AndrewBennet/ReadingList#50]
Hey there,
It's been a couple of weeks since I installed _Reading List_ application and that helped me a lot organizing my reading habit!

It's great to hear that you want to add the _iCloud sync_ but i liked to also ask your opinion about **redesigning** some pages like **search page** to look a bit more modern and clean.

#### Some notices here:
- It would be great to have an option for remaining inside the search tab after adding the book and remembering the previous searches.
- The app can have a top rank searched books (page or list or recommendation) too!

#### What do you think about a website ?
I strongly like to recommend the application to have a server and a website witch I can help with! What do you think ?

---
### Thank You For Your Great App
> Well done for this beautiful app @AndrewBennet and other team members, please accept my deepest thanks :heart:

#40 #3 #33

**Comment by AndrewBennet** [comment]
Hi there,

Thanks for reaching out - and sorry my reply is a bit delayed.

I'm always happy to hear suggestions and see ideas developed with others 👍  Redesigning certain pages to look more modern/clean sounds good. Perhaps you could draw some simple mockups to show your proposed design changes? Another contributor has proposed some changes to the search screen which you might be interested in seeing first: https://github.com/AndrewBennet/ReadingList/pull/46

An option to return to the search after adding a book could be good, but it may be less necessary with the change mentioned above. If you let me know some of changes you're thinking, or some sketches of a new user flow in the app, we could discuss them.

Currently I'm hesitant about adding a book recommendation service; the app's original premise was very much to exclude all social media-like features which I found to add a lot of bloat to apps like Goodreads. I'm sure some users may like the book recommendation, but I worry that for a lot of users it will just get in the way. If there's a way to make the very unobtrusive, then I would consider this, but I have always imagined it would be quite a lot of work, and therefore probably not worth it. Happy to discuss this though.

And finally: a server & website. I'm not sure exactly what you're proposing. The app already has a [marketing website](https://readinglist.app) (very basic statically generated site, hosted for free). But I think you're talking about a backend server for some app features? If so: it depends on whether the features require them. Given the choice, I'd rather not have to maintain a server and backend codebase - hence the preference for iCloud sync over some proprietary sync backend - but if you can propose an awesome feature that can only be done with a server, that could change my opinion. At the moment, I don't see any need for a server though.

Going forward, I'd suggest fleshing out some of these ideas in separate Issues, where we can discuss them. Then, if we're in agreement, you're very welcome to raise pull requests introducing the features.

Thanks again, and have a good weekend,
Andrew

**Comment by Farhaduneci** [comment]
### Thanks for replying
> I know you must be busy most of times, I appreciate you're attention.

- That's great hearing your positive responses about the changes mentioned above, About the Mock Up I need to say that I'm not a designer unfortunately but I'll send you something witch is in my mind ( I had a look at #46 design & I found it intresting for UX +1 for that @bryanjclark -  But I feel the absent of a  design schema for the project, I mean the colors, font-size and all these stuff witch I really think that @tailwindcss has done It well, I know that these might be useless for IOS development but the color codes and notes from [Refactoring UI](https://refactoringui.com) might help having a better UI over all )

- You said _An option to return to the search after adding a book could be good, but it may be less necessary_ that I accept 100%, it might be better to be replaced by a simple recent searches list witch opens whenever the user taps the search bar! **What do you think about this idea?** ( I'll include this part inside the Mock Up)

- About the recommendation service I need to I guess it **worth it** considering _It would be quite a lot of work_, I recommend implementation of this system ( Not an intelligent, powerful one needed now I guess using the white space inside the + page would be cool, Top searched books with their related info can be shown inside a grid to the user )

- My suggestion about the website is only useful for those they do not have an IOS device or they like using laptop ( Like me ) having access to these services online looks cool and easy to use to me and I have a lot of curiosity about this.

> That would be great fleshing out some of these ideas in separate Issues, I've never did this before do I need to take any actions or you only have the authority to do so ?

Thank you again for all this job, I wish you having an awesome weekend too,
Farhad

**Comment by ctipper** [comment]
I think the comment was about a webapp. 😳 Easily said not so easily done. Particularly with an iCloud backend. In my experience this only makes sense if you’re a megacorps with developers to burn. Stick to the app I say. And release please.

**Comment by AndrewBennet** [comment]
I'm afraid I agree with @ctipper above, that maintaining a webapp is beyond the scope of this project. Sure, it would be great - but realistically I won't have time to maintain essentially a whole other product on top of the app. Very happy to look at suggested changes to the app itself though 👍

**Comment by mika-n** [comment]
Leaving my comment here also. I went through numerous "reading/bookshelf" type of apps to keep track of books I would like to read and have already finished/read. Many other apps had loooots of unnecessary bloat which just made the app cumbersome to use for what I wanted to have. This ReadingList app fit the purpose of keeping track of ToRead vs AlreadyRead books great without any extra bloat (and had the support for picture of book covers). 

I recommend to keep the approach as "do one thing, but do it better than other apps". There are those social media/book recommendations/push messages type of apps all around GooglePlay and AppStore. Someone wanting those for sure finds an app which already provides those features. But to find a straight forward app like ReadingList is more difficult. Therefore ReadingList is a great alternative and should remain like that or it looses the original purpose.

If there ever would be a ReadingList web site then maybe it should be "just" straight forward web frontend to manage the personal ToRead/Reading/Finished book list (add/remove books, modify book details) and nothing else.
