### ISSUE TITLE
Feature Request: Import from Goodreads

### ISSUE THREAD

**Issue by DonniYH** [AndrewBennet/ReadingList#51]
Would be amazing if we could import our existing library straight from Goodreads and over to ReadingList.

I’m aware of the CSV import but this would make it so seamless.

**Comment by DonniYH** [comment]
Whoops, didn’t see the latest update.

**Comment by AndrewBennet** [comment]
Let me know how you find it! It's slightly annoying that I can't lookup the book cover images during the import - to get the cover images I think I'd have to connect to the Goodreads API and bring the data over that way instead, which would probably be a fair bit of work.

**Comment by DonniYH** [comment]
Yeah its not so ideal. 

I know of another developer who also developed a similar app to Reading list.

Alex Gerrese is the dev of [Summarize ](https://apps.apple.com/us/app/summarize-read-remember/id1469372414?ref=producthunt) which has a Goodreads import via logging in. 

Maybe you could in [contact with him](https://summarize.landen.co/) and see how he pulled it off.

Good luck!
